type: registry
version: '1.0'
name: ApplicationGroupStatus
targets:
  - api
description: "Application group status"

items:
  UNKNOWN:
    value: "UNKNOWN"
    description: "Unknown status"
  ACTIVE:
    value: "ACTIVE"
    description: "Active group"
  DELETED:
    value: "DELETED"
    description: "Deleted group"
