type: registry
version: '1.0'
name: ApplicationRoleType
targets:
  - python-main
  - ts-main
  - graphql-main
description: "Types of application roles"

items:
  UNKNOWN:
    value: "UNKNOWN"
    description: "Unknown role type"
  ADMIN:
    value: "ADMIN"
    description: "Administrator role"
  USER:
    value: "USER"
    description: "Standard user role"
  GUEST:
    value: "GUEST"
    description: "Guest role"
  CUSTOM:
    value: "CUSTOM"
    description: "Custom role"
