type: registry
version: '1.0'
name: ApplicationGroupRoleStatus
targets:
  - api
description: "Application group role assignment status"

items:
  UNKNOWN:
    value: "UNKNOWN"
    description: "Unknown status"
  ACTIVE:
    value: "ACTIVE"
    description: "Active role assignment"
  DELETED:
    value: "DELETED"
    description: "Deleted role assignment"
